version: '3.9'
services:
  dev_client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
  dev_server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
